### ISSUE TITLE
Allow for setting Gotenberg environment variables

### ISSUE THREAD

**Issue by timmw** [Kurt108/helm-charts#29]
Hey. Thanks for the Gotenberg chart!

It would be great if it were possible to set Gotenberg environment variables using helm values. I noticed the other charts in this repo allow it but not the Gotenberg one.

**Comment by timmw** [comment]
Thanks for the quick response. I've tested v3.0.0 of the gotenberg chart using the following values.yaml
```yaml
gotenberg:
  image:
    tag: 6.2.1
    repository: thecodingmachine/gotenberg
  env:
    open:
      MAXIMUM_WAIT_TIMEOUT: '250.0'
      DISABLE_UNOCONV: 'true'
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 600m
      memory: 512Mi
```
Seems to work well for me!
